version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - policy-net
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - policy-net
  opa:
    build:
      context: ./opa
    container_name: opa
    ports:
      - "8181:8181"
    networks:
      - policy-net

  auth-service:
    build:
      context: ./services/auth-service
    container_name: auth-service
    ports:
      - "8080:8080"
    environment:
      - OPA_URL=http://opa:8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/banking_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - opa
    networks:
      - policy-net
  
  transfer-service:
    build:
      context: ./services/transfer-service
    container_name: transfer-service
    ports:
      - "8081:8081"
    environment:
      - OPA_URL=http://opa:8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/banking_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - opa
    networks:
      - policy-net

  approval-service:
    build:
      context: ./services/approval-service
    container_name: approval-service
    ports:
      - "8082:8082"
    environment:
      - OPA_URL=http://opa:8181
    depends_on:
      - opa
    networks:
      - policy-net

networks:
  policy-net:
    driver: bridge

volumes:
  postgres_data: